"""Pydantic models for structured output."""

from warpt.models.list_models import (
    CompilerInfo,
    CPUInfo,
    CUDAInfo,
    FrameworkInfo,
    GPUInfo,
    HardwareInfo,
    ListOutput,
    MemoryInfo,
    PythonInfo,
    SoftwareInfo,
    StorageDevice,
)
from warpt.models.power_models import (
    DomainPower,
    GPUPowerInfo,
    PowerDomain,
    PowerSnapshot,
    PowerSource,
    ProcessPower,
    RAPLDomain,
)
from warpt.models.profile_models import (
    DeviceFingerprint,
    DeviceProfile,
    HardwareCategory,
    Observation,
    ObservationEnvironment,
)
from warpt.models.stress_models import (
    CPUSummary,
    CPUSystemResult,
    CPUTestResults,
    GPUDeviceResult,
    GPUSummary,
    GPUSystemResult,
    GPUTestResults,
    RAMSummary,
    RAMTestResults,
    StressTestExport,
    ThrottleEvent,
)

__all__ = [
    "CPUInfo",
    "DeviceFingerprint",
    "DeviceProfile",
    "CPUSummary",
    "CPUSystemResult",
    "CPUTestResults",
    "CUDAInfo",
    "CompilerInfo",
    "DomainPower",
    "FrameworkInfo",
    "GPUDeviceResult",
    "GPUInfo",
    "GPUPowerInfo",
    "GPUSummary",
    "GPUSystemResult",
    "GPUTestResults",
    "HardwareCategory",
    "HardwareInfo",
    "ListOutput",
    "MemoryInfo",
    "Observation",
    "ObservationEnvironment",
    "PowerDomain",
    "PowerSnapshot",
    "PowerSource",
    "ProcessPower",
    "PythonInfo",
    "RAMSummary",
    "RAMTestResults",
    "RAPLDomain",
    "SoftwareInfo",
    "StorageDevice",
    "StressTestExport",
    "ThrottleEvent",
]
